export const dummyData = [
  {
    id: 1,
    offer: '',
    name: 'Millet Dosa Batter',
    cta: 'Kick-start a Healthy Life!',
    subCta:
      'Enjoy perfectly natural and healthy dosas with this traditional recepie.',
    subscriptionPrise: '$85',
    ingredientsSrc: require('_assets/images/Ingredients/ingredient_millet.png'),
    prise: '$99',
    extraSpace: 0,
    bgColor: '#E74C22',
    source: require('_assets/images/Millet-Dosa-Batter/milletDosaBatter-3x.png'),
  },
  {
    id: 2,
    offer: '',
    name: 'Idli Batter',
    cta: 'Kick-start a Healthy Life!',
    subCta:
      'Enjoy perfectly natural and healthy dosas with this traditional recepie.',
    subscriptionPrise: '$85',
    ingredientsSrc: require('_assets/images/Ingredients/ingredient_idli.png'),
    prise: '$99',
    extraSpace: 0,
    bgColor: '#E78426',
    source: require('_assets/images/Idli-Batter/idliBatter-3x.png'),
  },
  {
    id: 3,
    offer: '',
    name: 'Dosa batter',
    cta: 'Kick-start a Healthy Life!',
    subCta:
      'Enjoy perfectly natural and healthy dosas with this traditional recepie.',
    subscriptionPrise: '$85',
    ingredientsSrc: require('_assets/images/Ingredients/ingredient_dosa.png'),
    prise: '$99',
    extraSpace: 0,
    bgColor: '#ECA51F',
    source: require('_assets/images/Dosa-Batter/dosaBatter-3x.png'),
  },
  {
    id: 4,
    offer: 'Introductory Offer',
    name: 'Combo Pack',
    cta: 'Kick-start a Healthy Life!',
    subCta:
      'Enjoy perfectly natural and healthy dosas with this traditional recepie.',
    subscriptionPrise: '$85',
    ingredientsSrc: require('_assets/images/Ingredients/ingredient_millet.png'),
    prise: '$99',
    extraSpace: 0,
    bgColor: '#86A438',
    source: require('_assets/images/Combo/combo-3x.png'),
  },
]
